dist: trusty
sudo: false
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
# see note here https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
branches:
  only:
  - master
  - dev
env:
  global:
    - NODE_ENV=production
before_install:
- openssl aes-256-cbc -K $encrypted_d6be824c40c2_key -iv $encrypted_d6be824c40c2_iv
  -in gae-client-secret.json.enc -out gae-client-secret.json -d
- npm install yarn -g
# was npm rebuild
- yarn --force --build-from-source
install:
- yarn run build
deploy:
  provider: gae
  # Skip cleanup so api_key.py and vendored dependencies are still there
  skip_cleanup: true
  keyfile: "gae-client-secret.json"
  project: "quantum-enigma-707"
notifications:
  slack: jamesnadeau:qYzgCRbDHYZsVH3JqfLzpwGo