# .github/workflows/main.yml

name: Trigger Netlify Build
on:
  schedule:
    # Run at 0400 daily
    - cron: '0 4 * * *'
jobs:
  build:
    name: Netlify Webhook to Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
